/* JFS Laundry AI — customer database + Knowledge Base AI */
(function(){const cfg=window.JFS_SUPABASE_CONFIG;if(!cfg||!window.supabase)return;window.jfsDb=window.supabase.createClient(cfg.url,cfg.key);window.JFS_ORDER_STATUS={pending:'Menunggu Jemput',processing:'Dalam Proses',ready:'Siap Diambil',completed:'Selesai',cancelled:'Dibatalkan'};window.jfsStatusLabel=s=>window.JFS_ORDER_STATUS[s]||s||'Menunggu Jemput';
async function getKbTenant(){if(window.dbTenant)return window.dbTenant;const id=new URLSearchParams(location.search).get('id')||'JFS-LAUNDRY-DEMO-001';const{data}=await jfsDb.from('jfs_public_tenant_catalog').select('tenant_code,business_name,address,city,province,whatsapp,phone,ai_enabled').eq('tenant_code',id).maybeSingle();window.dbTenant=data||null;return window.dbTenant}
function tokens(s){return String(s||'').toLowerCase().replace(/[^a-z0-9\s]/g,' ').split(/\s+/).filter(x=>x.length>2)}function score(q,text){const a=new Set(tokens(q)),b=tokens(text);return[...a].filter(x=>b.includes(x)).length}
async function priceAnswer(){const t=await getKbTenant();if(!t)return null;const{data,error}=await jfsDb.from('jfs_public_products').select('name,description,price,unit,category,is_active').eq('tenant_code',t.tenant_code).eq('is_active',true).gt('price',0).order('name');if(error||!data?.length)return null;const lines=data.map(x=>{const unit=x.unit||'unit';return `• ${x.name}: Rp ${Number(x.price||0).toLocaleString('id-ID')} / ${unit}`});return `Berikut tarif layanan yang tersedia:\n${lines.join('\n')}\n\nJika ingin memesan, pilih layanan pada form Pesan Laundry.`}
async function knowledgeAnswer(question){const t=await getKbTenant();if(!t)return null;const[k,p]=await Promise.all([jfsDb.from('jfs_public_knowledge').select('category,question,answer,keywords').eq('tenant_code',t.tenant_code).eq('is_active',true),jfsDb.from('jfs_public_products').select('name,description,price,unit,category').eq('tenant_code',t.tenant_code).eq('is_active',true)]);const docs=[...(k.data||[]).map(x=>({content:x.answer,score:score(question,`${x.category||''} ${x.question||''} ${x.answer||''} ${x.keywords||''}`)})),...(p.data||[]).map(x=>({content:`${x.name}: ${x.description||''} Harga Rp ${Number(x.price||0).toLocaleString('id-ID')} per ${x.unit||'unit'}.`,score:score(question,`${x.name} ${x.description||''} ${x.category||''} harga tarif`}))].sort((a,b)=>b.score-a.score);const best=docs.filter(x=>x.score>0).slice(0,2);return best.length?best.map(x=>x.content).join('\n'):null}
function getChatHistory(){return Array.isArray(window.jfsChatHistory)?window.jfsChatHistory.slice(-6):[]}function pushChat(role,content){window.jfsChatHistory=window.jfsChatHistory||[];window.jfsChatHistory.push({role,content:String(content||'').slice(0,1200)});window.jfsChatHistory=window.jfsChatHistory.slice(-6)}
async function kbSendMessage(){const i=document.getElementById('chat-input'),text=i.value.trim();if(!text)return;const historyBeforeMessage=getChatHistory();addBubble(text,true);pushChat('user',text);i.value='';try{const q=text.toLowerCase();if(/\b(harga|tarif|price|berapa|biaya)\b/.test(q)){const direct=await priceAnswer();if(direct){addBubble(direct);pushChat('assistant',direct);return}}
const tenantCode=new URLSearchParams(location.search).get('id')||'JFS-LAUNDRY-DEMO-001';try{const r=await fetch(`${window.JFS_SUPABASE_CONFIG.url}/functions/v1/laundry-customer-ai`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({tenant_code:tenantCode,message:text,history:historyBeforeMessage})});const b=await r.json();if(r.ok&&b.answer){addBubble(b.answer);pushChat('assistant',b.answer);return}}catch(e){console.warn('AI function unavailable',e)}let r=await knowledgeAnswer(text);if(!r)r='Saya belum menemukan informasi itu di data laundry. Agar tidak memberi informasi yang salah, silakan hubungi toko melalui WhatsApp untuk pertanyaan khusus.';addBubble(r);pushChat('assistant',r)}catch(e){console.error('Chatbot error',e);const fallback='Maaf, data layanan sedang tidak dapat dimuat. Silakan coba lagi atau hubungi toko melalui WhatsApp.';addBubble(fallback);pushChat('assistant',fallback)}}
document.addEventListener('DOMContentLoaded',()=>{if(document.getElementById('chat-input')){window.jfsSendMessage=kbSendMessage;window.sendMessage=kbSendMessage}});})();
